title: Conventional Commits
descriptions: open-source maintainer, squash feature branches onto `master` and write a standardized commit message while doing so.

# Should be in the form of
# <machine readable key>: <human readable label>
languages:
  en: english
  pl: polish
  it: italian
  zh-Hans: 简体中文
  es: spanish

versions:
  - 1.0.0-beta
  - 1.0.0-beta.1
  - 1.0.0-beta.2

current_version: 1.0.0-beta.2

# Default author, for when none is set
author: Benjamin Coe

gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-redirect-from
  - kramdown

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"

exclude: ['docker-compose.yml', 'config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
